version: '3'

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb-reto
    ports:
      - "27017:27017"
    # volumes:
      # - ./data:/data/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js